### ISSUE TITLE
Should we have an quick "no symptoms" option 

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#126]
Idea from twitter: https://twitter.com/pjarvilehto/status/1243539176437551106?s=20 "UX puolella kannattaisiko lisätä myös helppo "ei oireita" vaihtoehto alkuun, niin saataisiin myös terveiltä helpommin kuittaukset."

**Comment by jnissin** [comment]
Yes. We should!

**Comment by jnissin** [comment]
I think this is somewhat related to: #155

**Comment by mahdava** [comment]
We're opting for not going down this route to avoid a significant distortion of the responses; therefore, I'm closing this issue and adding an extra note as well in #155.
