### ISSUE TITLE
Add question: Have you been tested for COVID-19?

### ISSUE THREAD

**Issue by jnissin** [futurice/symptomradar#130]
From data science perspective it would be interesting to have a question: "Have you been tested for COVID-19?". The options could be: No / Yes, negative / Yes, positive.

This question could provide us with a partially labeled self-reported symptoms dataset for COVID-19. In addition it would provide us with information how many participants have had COVID-19 tests in given areas. Cross-referencing that with areas that show a lot of symptoms, but have low rate of testing might also be interesting. 

To keep the form as short and concise as possible we could remove the question: "Do you suspect you have been infected with COVID-19?" / "Epäiletkö, että olet saanut koronavirustartunnan?" in favor of this new question. It's also possible to have both questions to maintain backwards compatibility with the data.

**Comment by siniauer** [comment]
Decided not add this question. We'll focus on collecting symptoms.

**Comment by jnissin** [comment]
Thanks for the response!

I am still curious regarding the rationale behind the decision. As it stands currently the service is in fact focused on collecting symptoms, but is also collecting data about the visitor's background with questions like "Are you a smoker?", and even COVID-19 specific questions such as "Do you suspect you have been infected with COVID-19?". The case with this question would be no different.

We have received multiple feedbacks from relevant professionals requesting a question such as this, claiming that it would bring additional value to the dataset. I agree with these assesments as a data scientist. If the concern is related to asking about a confirmed test result/diagnosis from the user, I don't see how their privacy could be compromised as no PII is saved from the users. While I do not have a professional understanding of the legality of the question, I do not see the difference between asking "Have you been tested for COVID-19?" or "Have you had cancer?" or "Do you suffer from migraines?", which all seem like questions one should be able to ask for research purposes.

If the problem is specifically about asking the outcome of the test, even asking the question "Have you been tested for COVID-19?" with a simple yes/no answer would provide valuable additional information. Lastly, answering the question should be of course optional so users who do not wish to disclose this information would not have to. I would strongly encourage the team to confirm that there is a problem asking this kind of a question from the relevant authorities or law professionals and only then abandon the question. If such a problem doesn't exist, I would strongly encourage including the question in a future release because of its relevance for the ongoing COVID-19 epidemic and for the future value of the collected dataset.

I would strongly encourage the team to confirm that there is a problem asking this kind of a question from the relevant authorities or law professionals and only then abandon the question. If the problem doesn't exist I would strongly encourage including the question in a future release because of its relevance for the ongoing COVID-19 epidemic and for the future value of the collected dataset.

**Comment by Doniee** [comment]
This has been discussed elsewhere, closing for now.
