### ISSUE TITLE
Request for contibutions: Translate all embed texts to english

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#135]
We should translate the Oiretutka embed to english. If you want to help, please provide english translations of this page (text below): https://www.oiretutka.fi/embed/v1/

The issue #127  is about technical framework for translations.

To help with translations, please just comment below with translated version and we'll take it from there.

**Pre-embed texts**

> Kerro, onko sinulla oireita vai ei: auta selvittämään, miten koronavirus leviää
> Suomalaiset mediat pyytävät Oiretutka-palvelussa lukijoiltaan tietoa, onko heillä koronavirukseen viittaavia oireita vai ei.
> 
> Kertomalla tilanteestasi – myös terveenä – voit auttaa mediaa kertomaan paremmin siitä, miten virus leviää. Oiretutkaan tallennettuja tietoja ei voi yhdistää vastaajaan. Vastauksia julkaistaan yhteenvetona ja yksittäisinä vastauksina. Kysely on suunniteltu yhteistyössä Helsingin yliopiston kansanterveystieteen osaston kanssa.
> 
> Palvelua ei ole tarkoitettu yksittäisen henkilön opastamiseksi terveyteensä liittyen tai ohjaamiseksi terveydenhuoltoon.
> 
> Lue lisää tietosuojasta täältä.

**The actual questions of the embed**

> MILLAISIA OIREITA SINULLA ON?
> Kuumetta
> 
> alle 38,5 astetta
> 
> yli 38,5 astetta
> 
> Yskää
> 
> ei
> 
> lievää
> 
> voimakasta
> 
> Vaikeuksia hengittää
> 
> Lihaskipuja
> 
> Päänsärkyä
> 
> Kurkkukipua
> 
> Nuhaa
> 
> Vatsaoireita kuten ripulia, pahoinvointia tai vatsakipuja
> 
> Hajuaistin tai makuaistin heikkenemistä
> 
> TERVEYDENTILA
> 
> Millainen on yleisvointisi?
> 
> jaksan olla jalkeilla
> 
> jaksan olla jonkun verran jalkeilla ja hoitaa välttämättömät kotiaskareet
> 
> en juurikaan jaksa nousta vuoteesta
> 
> Kuinka monta päivää oireesi ovat kestäneet? (Voit jättää vastaamatta, jos sinulla ei ole oireita)
> 
> Onko sinulla lääkehoitoa vaativa pitkäaikaissairaus?
> 
> Tupakoitko?
> 
> Epäiletkö, että olet saanut koronavirustartunnan?
> 
> YLEISTIEDOT
> 
> Ikä
> 
> Sukupuoli
> 
>  nainen  mies  muu
> 
> Postinumero

**After submitting the form**

> Kiitos vastauksistasi.
> 
> Pyydämme, että palaat kertomaan oireistasi kolmen päivän kuluttua. Jos täytät kyselyn uudelleen samalla laitteella 14 vuorokauden kuluessa, vastaukset voidaan yhdistää keskenään, jolloin tiedoista on enemmän hyötyä. Tiedot ovat silti anonyymejä, eikä niitä voi palvelussa yhdistää vastaajaan. Lue lisää tietosuojasta täältä.
> 
> Kun vastauksia on kertynyt riittävästi, niitä aletaan tutkia yhteistyössä terveydenhuollon asiantuntijoiden kanssa.
> 
> Jos sinulla on hengitysvaikeuksia, kova kuume tai et jaksa nousta vuoteesta, ota yhteys terveydenhuoltoon. Jos epäilet sairastuneesi koronaviruksen aiheuttamaan tautiin ja haluat tehdä oirearvion, siirry Terveyden ja hyvinvoinnin laitoksen ylläpitämään Omaolo.fi-palveluun.

**Comment by jsslnt** [comment]
**Pre-embed**

`Let us know if you have symptoms or not: help us determine how COVID-19 spreads.

Finnish media are imploring their users to disclose whether or not they are experiencing symptoms pointing to COVID-19 via the Symptom Radar service

By telling us about your situation – even if you’re completely healthy – you can help media to better cover the spread of the virus. Any data inserted into Symptom Radar can not be connected back to the user. The replies will be published both in compiled format and as standalone replies. The questionnaire was designed in collaboration with the University of Helsinki. 

The service is not meant to be used for advice on personal health or whether or not to seek medical aid. `

**Comment by sannanaapuri** [comment]
“Let us know if you are experiencing symptoms or not, and help us determine how COVID-19 spreads.

Finnish media providers are requesting information from their readers to let them know if they are currently experiencing any potential coronavirus symptoms via the Oiretutka service. By sharing anonymous information about your situation- even if you are currently feeling completely healthy- you can help the media to understand the spread of the virus, and cover the spread of the virus more effectively and accurately. Any responses provided via the Oiretutka service questionnaire are totally anonymous, and cannot be traced back to the respondent. The questionnaire has been created in collaboration with the department of Public Health Research at Helsinki University.
This service is not meant to be used as an aid to self-diagnose symptoms, or as a guide to seek medical aid."

**Comment by jsslnt** [comment]
**Questions**
What kinds of symptoms are you experiencing?

Fever 
less than 38.5 degrees
more than 38.5 degrees

Coughing
No  Yes
Mild 
Strong

Breathing difficulties

Muscle soreness (muscle pain?)

Head ache

Sore throat

The Sniffles (/Runny nose)

Stomach problems such as diarrhea, nausea or abdominal pain

Loss of sense of smell or taste

OVERALL HEALTH

How do you feel generally?

I have no problems staying awake

I can stay awake long enough to handle necessary chores at home

I can’t get out of the bed much

How long have you had these symptoms (if you are not experiencing any symptoms, leave this blank)

Do you have any long-term illnesses that require medication?

Do you smoke?

Do you suspect you may have contracted COVID-19?

GENERAL

Age

Gender 

female/male/other

Postal code

**Comment by sannanaapuri** [comment]
Small adjustments to Jesse's questions above :)

Breathing difficulties-> Difficulties in breathing
Head ache -> Headache
The sniffles -> Runny nose
Loss of sense of smell or taste -> Loss of smell or taste
I can’t get out of the bed much -> I have difficulties getting out of bed

**Comment by jsslnt** [comment]
Good stuff @sannanaapuri! Regarding the first one: Google seems to support both options

**Comment by sannanaapuri** [comment]
Thank you for your response.

We kindly request that you report your symptoms via the Oiretutka service again in 3 days' time. By filling in the questionnaire using the same device within 14 days, your responses can be connected to each other, making the information provided even more valuable. Your responses will still remain anonymous, and cannot be traced back to the respondent. You can read more about our Data Protection and Privacy Procedure here.

Once enough responses have been collected, these will be studied in collaboration with medical experts.

If you are experiencing difficulties in breathing, a high fever, or cannot get out of bed, please contact your medical health provider. If you suspect that you have contracted the coronavirus and want to check your symptoms, please visit (_english service name here_)'s Omaolo.fi service.

**Comment by EsaMakinen** [comment]
Folks: thank you! We've now added the support and these translations, and soon we will be launching the translated version: https://github.com/futurice/symptomradar/pull/178
