### ISSUE TITLE
Make it clearer that the service remembers you

### ISSUE THREAD

**Issue by jnissin** [futurice/symptomradar#138]
Currently, I have received a lot of feedback that people don't realize that the service remembers you and connects to your earlier answers. People say that it's difficult to remember the exact answers that they gave previously, which makes giving consistent lateral information difficult. We should come up with a way to help the user give consistent answers across time and make it explicit that their answers are grouped together if they answer using the same client (with the cookie). Also, the proposed three days seems like a long time period between updates as the symptoms can progress on a daily basis.

Possible solutions
* Optional email field with a reminder to update your symptoms
* Autopopulating the fields according to the identity in the cookie (possible security issue?). Could this be optionally enabled by clicking remember my answers in the form or something?
* To clarify that the service remembers you could we show how much time has passed since you last updated your symptoms?

**Comment by jareware** [comment]
@Doniee you were working on this..?

**Comment by Doniee** [comment]
Text to show for returning users https://github.com/futurice/symptomradar/issues/36#issuecomment-603849447
