### ISSUE TITLE
Quick fix needed regarding Omaolo / feedback text

### ISSUE THREAD

**Issue by siniauer** [futurice/symptomradar#142]
Omaolo is not run by THL, it's service by Sotedigi that has been created by THL, Duodecim and Sotedigi Oy that is government company. 

So to replace the last paragraph in the text that you get after submitting the form:

Jos sinulla on hengitysvaikeuksia, kova kuume tai et jaksa nousta vuoteesta, ota yhteys terveydenhuoltoon. Jos epäilet sairastuneesi koronaviruksen aiheuttamaan tautiin ja haluat tehdä oirearvion, siirry valtion kehitysyhtiö Sotedigin ylläpitämään Omaolo.fi-palveluun.

**Comment by siniauer** [comment]
@Doniee could you do this?

**Comment by Doniee** [comment]
Yeah I can do it!

**Comment by siniauer** [comment]
@Doniee oh wait a sec

**Comment by siniauer** [comment]
@Doniee Esa says let's jut drop the provider of Omaolo, so:

Jos sinulla on hengitysvaikeuksia, kova kuume tai et jaksa nousta vuoteesta, ota yhteys terveydenhuoltoon. Jos epäilet sairastuneesi koronaviruksen aiheuttamaan tautiin ja haluat tehdä oirearvion, siirry Omaolo.fi-palveluun.
