### ISSUE TITLE
Change text from embed thank you text

### ISSUE THREAD

**Issue by Knuutilae** [futurice/symptomradar#150]
In the end there is a text: ...jos haluat tehdä oirearvion, siirry Terveyden ja hyvinvoinnin laitoksen ylläpitämään Omaolo.fi-palveluun. That should be changed to: ...jos haluat tehdä oirearvion, siirry Sotedigi Oy:n ylläpitämään Omaolo.fi-palveluun.

As the service is not by THL but Sotedigi Oy.

**Comment by Doniee** [comment]
This should be done already, based on the discussion here https://github.com/futurice/symptomradar/issues/142

**Comment by Knuutilae** [comment]
Ah. Good. I'll close this.
