### ISSUE TITLE
Changing the questionnaire to grid

### ISSUE THREAD

**Issue by Knuutilae** [futurice/symptomradar#155]
The questionnaire starts to be quite long. It could be useful in changing it to a grid so it would be more user friendly and dense.

**Comment by jnissin** [comment]
+1 for this! The yes/no questions could easily be compressed into a single container where the user could quickly tap the symptoms they have or select "no symptoms" which would disable the other symptoms.

**Comment by kilian-kottmeier** [comment]
The label of the symptoms is too long to show the label and the yes/no button in one line, (especially on smaller mobile devices). Breaking the grid layout would then be confusing.
And removing the lines and moving the questions closer together will leave too little space to comfortably tab the buttons. 

<img width="653" alt="Screenshot 2020-04-01 at 16 41 08" src="https://user-images.githubusercontent.com/42265080/78144255-0a6b0d80-7438-11ea-87d6-6d6bb0be20e4.png">

**Comment by kilian-kottmeier** [comment]
About the no symptoms answer: 
We should have it but I think we shouldn't hide the symptoms because that way people know what kind of symptoms we mean. Then with one glance, people can decide whether or not they have any of the listed symptoms.

**Comment by mahdava** [comment]
Extra addition to the no symptoms #126 
We're opting for not going down this route to avoid a significant distortion of the responses; therefore, let's not take it into account in this issue either.
