### ISSUE TITLE
Create city level data export for first visualization

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#164]
The first city-level visualization of the data needs following aggreagated data set, row by row:
- City
- City population
- Total number of replies in city
- Different symptoms reported, by sympton type (Fever: no fever, slight fever, high fever)
- Remove the following from data before aggregation: answers with CF code other than FI; postal numbers that are wrong and/or don't match to a city

**Comment by jareware** [comment]
This data set should then be made available as:

```
https://data.oiretutka.fi/per-city.json
```

...or some such filename.
