### ISSUE TITLE
Create all the non-visualization things needed for Oiretutka.fi

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#167]

**Comment by siniauer** [comment]
The text for the site:

Oiretutka on Helsingin Sanomien ja teknologiayhtiö Futuricen kehittämä hanke, jonka tarkoituksena on kerätä suomalaisilta tietoja heidän kokemistaan oireista. Myös muita suomalaisia medioita osallistuu tiedonkeruuseen. Tiedon avulla on tarkoitus ymmärtää paremmin, miten koronavirus mahdollisesti leviää Suomessa. Hanke tehdään avoimen lähdekoodin periaatteella. 

Tiedot ovat kerätty kyselylomakkeen avulla. Tällä sivustolla näytämme kyselyn tuloksia.  
Lue lisää tietosuojasta täältä. (And for this last line, let's put a link to the https://www.oiretutka.fi/tietosuojalauseke.html page)

@Doniee @kilian-kottmeier

**Comment by jareware** [comment]
Done in #204
