### ISSUE TITLE
Reported bug from a user

### ISSUE THREAD

**Issue by Knuutilae** [futurice/symptomradar#187]
Bug that might have been depending on the user but just FYI

>Yritin eilen tai toissapäivänä kolme kertaa vastata kysymyksiin tuossa Hesarissa mainostettuun Oiretutkaan ja ei kertaakaan onnistunut? vastaukset ei lähtenyt vaan tuli jotain ruutua punaisella... en nyt muista mitä tarkalleen...
>
>Vastata olen yrittänyt normaalilla kannettavalla tietokoneella Lenovo ThinkPad  T430s ja käyttöjärjestelmänä Win 10  sekä selaimena  Crome.
>
>Nyt kuitenkin kokeilin taas äsken vastata ja vastaus lähti ja ilmeisesti meni perillekin kun tuli kiitos viesti, joten nyt näyttää toimivan? Olisiko ollut heti uudekseltaan liian paljon käyttäjiä/ vastaajia?

**Comment by jareware** [comment]
I'm 97% sure this happened during a deploy. As it stands, we have a nagging issue in the release process where if BOTH:

* we deploy an update that changes validation rules (e.g. adds a mandatory field, like `v1.2` did), AND
* the participant happens to have loaded the frontend while the old release is up, but when submitting to the backend, the new release is already up

There's various ways this can be handled better, but given how few users this has affected thus far based on backed error logs (on the order of 15, from about 120k responses), we just haven't had time to do do anything about it, and some users just got unlucky. :confused:

**Comment by jareware** [comment]
This has not been reported again, and it should be exceedingly rare.

Will close for now.
