### ISSUE TITLE
Small viewports on Mobile 

### ISSUE THREAD

**Issue by kilian-kottmeier** [futurice/symptomradar#216]
On 320 viewports the website breaks in every screen. When testing the site with safari on iPhone SE I got the attached views. 

Concrete issues: 
- The map legend is overlapped by buttons 
- In the detail view, the word "koronavirustartunnasta" runs out of the screen
- City selector reaches out of the screen.

![Image from iOS (2)](https://user-images.githubusercontent.com/42265080/78793560-3e57ad00-79bb-11ea-8803-99af6da3f227.png)
![Image from iOS](https://user-images.githubusercontent.com/42265080/78793562-3f88da00-79bb-11ea-99aa-d05e4f3be829.png)

![Image from iOS (1)](https://user-images.githubusercontent.com/42265080/78793552-3bf55300-79bb-11ea-8056-178e89e08110.png)

**Comment by Doniee** [comment]
This has been improved in a couple different pull requests so I'll close this.
Here's the current state on small iOS screen:
![image](https://user-images.githubusercontent.com/5812075/79343178-c2b7ac00-7f36-11ea-8f22-05c41d0419ad.png)
And the modal on a small screen
![image](https://user-images.githubusercontent.com/5812075/79343600-3e195d80-7f37-11ea-8f6b-51ab723aa8ba.png)
