### ISSUE TITLE
Bug: error message should clear after user succesfully replies

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#221]
A cal from user: we leave the error on after succesful answer

**Comment by Doniee** [comment]
Did this happen in the oiretutka.fi embed version? If yes, I noticed it yesterday too, fixed this morning and it was merged a while ago https://github.com/futurice/symptomradar/pull/217
(But probably not in production yet.)

**Comment by jareware** [comment]
Not in prod yet. :sweat_smile:
