### ISSUE TITLE
Create postal number level open data

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#229]
The postal number are data set should contain same data as is in city level data set. And:
- Remove all postal number areas with less than 10 replies. 
- Remove all non-valid postal number areas.
- Remove postal number areas with population smaller than 500
- Do not include ages or any other personal data
- Include the population and the name of the postal number area

**Comment by cutepig** [comment]
Currently blocked by missing postal area data for all "valid" postal areas that should include:

- Postal code
- Name of the postal area
- Population
