### ISSUE TITLE
Create data set for last week in city level

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#232]
This is city-level data, but only for last week. When this is done we should also enable the user to choose between latest/full data.

**Comment by EsaMakinen** [comment]
The last week here means the current day and six previous full days.

**Comment by cutepig** [comment]
Question about filtering, quoting the related PR:
> City data isn't currently filtered based on number of responses, which is something to discuss. In total accumulated data cities with less than 25 responses are filtered, what are the requirements here?
