### ISSUE TITLE
Form tweaks: Add question and add one option

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#69]
1. For some reason head ache had dropped out! After muscle pains (Lihaskipuja), we should have
Päänsärkyä (kyllä / ei)
2. Vaikeuksia hengittää, should have the same response options as "Yskää", so ei/lievää/voimakasta

**Comment by siniauer** [comment]
The professor said that yes, let's add the question about smell and taste, it seems to be relevant. @Doniee : 
Muutoksia haju- tai makuaistissa (kyllä / ei )

**Comment by EsaMakinen** [comment]
This was done
