### ISSUE TITLE
Introduce a linter to the project

### ISSUE THREAD

**Issue by quarian** [futurice/symptomradar#84]
While there is a `.prettierrc` in the project, I didn't find a `eslint` or other linter solution. Having this would remove style arguments from contributions ("If it passes linter, it's in line with the style guide").

Also, TS compiler with a linter would provide a functioning level of hygiene at this time of fast development.

Could be augmented with a automatic linting on a PR or a `husky` powered git hook.

**Comment by olpeh** [comment]
I started some work on this earlier, but will need to wait a bit due to having to restructure/reorganize the project a bit.
